repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Check https://github.com/psf/black/releases for the latest
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.3  # Check https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
